version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
        # Install dependencies required to run the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/eDiary_ManagementSystem/*.py || true
artifacts:
    files:
        - '**/*'
